# Generated by Django 3.0.2 on 2020-02-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200209_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(),
        ),
    ]
